# Generated by Django 5.2 on 2025-05-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publication_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('music', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('tone', models.CharField(choices=[('😒', 'Passif-agressif'), ('🙌', 'Honnête'), ('😂', 'Ironique'), ('😢', 'Touchant'), ('✨', 'Classe')], default='🙌', max_length=2)),
                ('format', models.CharField(choices=[('classic', 'Classique'), ('fati', 'Fati'), ('canva', 'Canva'), ('immersive', 'Immersive')], default='classic', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
