# Generated by Django 5.2.1 on 2025-05-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_publication_music_publication_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='format',
            field=models.CharField(choices=[('classic', 'Classique'), ('fati', 'Fati'), ('canva', 'Canva'), ('immersive', 'Immersive')], default='classic', max_length=10),
        ),
    ]
